/*
 * Loan
 *
 * Branch read docs
 *
 * API version: 0.0.1
 * Contact: shivukumar076@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

// @title           Loan Sanction API
// @version         1.0
// @description     Loan Sanction Wirte server.
// @termsOfService  http://swagger.io/terms/

// @contact.name   API Support
// @contact.url    http://www.swagger.io/support
// @contact.email  shivukumar076@gmail.com

// @license.name  Apache 2.0
// @license.url   http://www.apache.org/licenses/LICENSE-2.0.html

// @host      localhost:3081
// @BasePath  /api/v1

package main

import (
	"log"

	"github.com/SbFinanceFbd/BranchRead/docs"
	config "github.com/SbFinanceFbd/BranchRead/src/main/go/config"
	sw "github.com/SbFinanceFbd/BranchRead/src/main/go/controller"
	l "github.com/SbFinanceFbd/golib/logger"
)

func init() {
	logFileName := config.AppConfig.MustGetString("log.file.name")
	appName := config.AppConfig.MustGetString("app.name")
	l.InitLogger(logFileName, appName)
	l.Debug.Printf("::init:: Log File Name-> %v, App Name-> %v\n", logFileName, appName)
	config.Init()
}

func main() {
	docs.SwaggerInfo.Title = config.AppConfig.MustGetString("docs.SwaggerInfo.Title")
	docs.SwaggerInfo.Description = config.AppConfig.MustGetString("docs.SwaggerInfo.Description")
	docs.SwaggerInfo.Version = config.AppConfig.MustGetString("docs.SwaggerInfo.Version")
	docs.SwaggerInfo.Host = config.AppConfig.MustGetString("docs.SwaggerInfo.Host")
	docs.SwaggerInfo.BasePath = config.AppConfig.MustGetString("docs.SwaggerInfo.BasePath")
	docs.SwaggerInfo.Schemes = []string{"http", "https"}

	router := sw.NewRouter()

	log.Fatal(router.Run(":" + config.AppConfig.MustGetString("port")))
}
